# Site settings
title: Dave Delgado
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dave Delgado
user_description: Soy estudiante de la universidad de Guayaquil, en la carrera de Ingenieria en Software, esta carrera me interesó mucho desde un pinrcipio ya que desde pequeño he tenido este gusto por cosas relacionadas con software, hardware, etc... A mis 10 años empezé a crear mis primeros programas con Visual Studio, programas muy basicos, despues fui creando paginas webs con simple html. Al pasar 4 años, yo era conocido en grupos de internet por "saber" crear pequeñas cosas, y fue aqui donde me dieron la oportunidad de ser moderador en una pagina de juegos llamada <b>NPlay</b>, la cual duré unos meses, y desde todo este tiempo hasta la actualidad he ido cogiendo experiencia, y se de otras tecnicas en software.
user_title: Lineamientos para el buen uso de la lengua escrita
email: dave.delgadog@hotmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
